name: Release (Tauri)

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  tauri-build:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install frontend deps
        run: npm ci

      # Linux braucht WebKit & Co. – sonst schlägt der Build gern fehl
      - name: Install Linux system deps
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev libayatana-appindicator3-dev \
            webkit2gtk-4.1 libwebkit2gtk-4.1-dev \
            libssl-dev librsvg2-dev patchelf

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Tauri CLI
        run: npm i -D @tauri-apps/cli

      - name: Build & Upload (tauri-action)
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tauriScript: npm run tauri
          args: --verbose
          tagName: ${{ github.ref_name }}
          releaseName: "QueueFlow ${{ github.ref_name }}"
          releaseDraft: false
          prerelease: false
